apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: servicea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: dnivra26/servicea:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http-port
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: servicea
spec:
  ports:
  - name: http-web
    port: 8081
    targetPort: 8081
  selector:
    app: servicea
