apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servicec-lb
spec:
  host: servicec.servicec.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN