apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servicec-cb-policy
spec:
  host: servicec.servicec.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 7
      interval: 5m
      baseEjectionTime: 15m