apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: servicec-timeout
spec:
  host: servicec.servicec.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms