apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicec-route
spec:
  hosts:
  - servicec.servicec.svc.cluster.local
  http:
  - route:
    - destination:
        host: servicec.servicec.svc.cluster.local
        subset: v2
      weight: 25
    - destination:
        host: servicec.servicec.svc.cluster.local
        subset: v1
      weight: 75