apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serviceb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
      - name: serviceb
        image: dnivra26/serviceb:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http-port
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: serviceb
spec:
  ports:
  - name: http-web
    port: 8081
    targetPort: 8081
  selector:
    app: serviceb
